version: '3'

services:
  db:
    image: mariadb:10.6.15
    ports:
      - "3306:3306"
    environment:
      - MARIADB_DATABASE=market
      - MARIADB_ROOT_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1